#!/usr/bin/env python3
"""Regenerate the census block inside the hand-written docs.

Every audit batch moves the published / held / captured counts, and three prose surfaces restate
them. Those sentences were wrong within a batch of being written — twice — because a count copied
from a terminal into markdown is a *quote* of a moment, not a fact about the catalog. So the
numbers now live in one generated block between sentinels, emitted from `catalog-stats.json` by
`make build`, and `make verify --check` fails a doc whose census has drifted.

Qualitative prose stays hand-written: this script never touches a sentence, only the block.
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from typing import Any, Dict, List

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
BEGIN = "<!-- census:begin -->"
END = "<!-- census:end -->"
TARGETS = ["README.md", "docs/AGENT_ACCESS.md", "docs/AUDIT_PROTOCOL.md"]


def _test_count() -> int:
    with open(os.path.join(REPO, "pipeline", "tests", "test_pipeline.py"), encoding="utf-8") as fh:
        return len(re.findall(r"^\s*def test_", fh.read(), re.M))


def _capture_census() -> Dict[str, int]:
    d = os.path.join(REPO, "pipeline", "raw", "deep_captures")
    caps = []
    for name in sorted(os.listdir(d)):
        if name.endswith(".json"):
            with open(os.path.join(d, name), encoding="utf-8") as fh:
                caps.append(json.load(fh))
    return {
        "captured": len(caps),
        "with_repo": sum(1 for c in caps if (c.get("links") or {}).get("repo")),
        "with_numbers": sum(1 for c in caps if c.get("numbers")),
    }


def render(stats: Dict[str, Any]) -> List[str]:
    admitted = (stats.get("coverage") or {}).get("published_total", stats.get("total", 0))
    pub = stats.get("audited_published", 0)
    pool = stats.get("pool_records", 0)
    held = stats.get("pool_audited_held", 0)
    never = stats.get("pool_unaudited", 0)
    caps = _capture_census()
    haz_p = stats.get("records_hazarded", 0)
    haz_h = stats.get("records_hazarded_held", 0)
    tests = _test_count()
    return [
        BEGIN,
        f"- **{pub} of {admitted}** admitted records are published — this catalog is audited-only — and "
        f"**{pool}** sit in `data/pool.json`: {held} captured, scored and held for cause · {never} never "
        f"captured at all.",
        f"- **{caps['captured']}** project pages have been deep-captured, {caps['with_numbers']} of them "
        f"with a recorded figures table (claims written down with a denominator — whether they then proved "
        f"checkable is each record's `numbers_add_up`), and {caps['with_repo']} linking a repository we "
        f"could verify against `api.github.com`. Hazard notes sit on {haz_p} published and {haz_h} held records.",
        f"- {tests} pipeline tests, every surface regenerated by `make build`, and `make verify` fails the "
        f"build if this block and `catalog-stats.json` ever disagree — including this block.",
        END,
    ]


def patch(path: str, block: List[str], check: bool) -> bool:
    with open(path, encoding="utf-8") as fh:
        src = fh.read()
    body = "\n".join(block)
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    found = pat.findall(src)
    if not found:
        print(f"  ✗ {os.path.relpath(path, REPO)}: no census sentinels")
        return False
    stale = [b for b in found if b.strip() != body.strip()]
    if check:
        if stale:
            print(f"  ✗ {os.path.relpath(path, REPO)}: census block is stale "
                  f"({len(stale)} of {len(found)} region(s) disagree with the built stats)")
            return False
        print(f"  ✓ {os.path.relpath(path, REPO)}: census current")
        return True
    if not stale:
        print(f"  = {os.path.relpath(path, REPO)}: unchanged")
        return True
    src2 = pat.sub(lambda m: body, src)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(src2)
    print(f"  ✎ {os.path.relpath(path, REPO)}: census regenerated")
    return True


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail instead of rewriting (used by make verify)")
    args = ap.parse_args()
    with open(os.path.join(REPO, "web", "public", "catalog-stats.json"), encoding="utf-8") as fh:
        stats = json.load(fh)
    block = render(stats)
    ok = True
    for rel in TARGETS:
        p = os.path.join(REPO, rel)
        if not os.path.exists(p):
            continue
        ok = patch(p, block, args.check) and ok
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
